title: Markham Community Robotics Space Invaders
author: FRC Team 6866
email: frcteam6866@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Markham Community Robotics is a local, student-led robotics organization that competes in the FIRST Robotics Competition.
baseurl: "/"
url: "mcrobotics.ca"

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed

plugins:
  - jekyll-sitemap