title: Markham Space Invaders
author: FRC Team 6866
email: frcteam6866@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Markham Community Robotics ( FRC Team 6866 - Space Invaders) is a local, student-led robotics organization that competes in the FIRST Robotics Competition.
baseurl: "/"
url: "https://mcrobotics.ca"

twitter: frc6866
github: frcteam6866
instagram: frc6866

sass:
  style: compressed

plugins:
  - jekyll-sitemap

excerpt_seperator: <!--more-->
